apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: leesah-dokumentasjon
  namespace: leesah-quiz
  labels:
    team: leesah-quiz
spec:
  image: {{image}}
  port: 4321
  liveness:
    path: /isAlive
    initialDelay: 10
  readiness:
    path: /isReady
    initialDelay: 10
  ingresses:
    - "https://leesah.io"
  resources:
    limits:
      memory: 768Mi
    requests:
      cpu: "50m"
      memory: 128Mi