apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: quizmaster
  namespace: leesah-quiz
  labels:
    team: leesah-quiz
spec:
  image: {{image}}
  port: 8080
  ingresses:
    - https://leesah-quizmaster.intern.dev.nav.no
  liveness:
    failureThreshold: 10
    initialDelay: 20
    path: /alive
    timeout: 1
  readiness:
    initialDelay: 20
    path: /ready
    timeout: 1
  replicas:
    cpuThresholdPercentage: 90
    max: 1
    min: 1
  accessPolicy:
    outbound:
      rules:
        - application: "*"
  resources:
    limits:
      cpu: 2000m
      memory: 5120Mi
    requests:
      cpu: 100m
      memory: 1024Mi
  prometheus:
    enabled: true
    path: /metrics
  kafka:
    pool: nav-dev
  env:
    - name: QUIZ_TOPIC
      value: leesah-quiz.leesah-rapid-v2
    - name: QUIZRAPID_AUTO_COMMIT
      value: "false"