name: Deploy produktside

on:
  push:
    branches:
      - main
      - astro-doks

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Yarn install
        working-directory: doks
        run: yarn install
      - name: Yarn build
        working-directory: doks
        run: yarn build
      - name: Upload static files to CDN
        id: upload
        uses: nais/deploy/actions/spa-deploy/v2@master
        with:
          team: leesah-quiz
          source: doks/dist
          ingress: https://leesah.io
          ingressClass: nais-ingress-external
          cluster: prod-gcp
          environment: prod
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
      - run: echo "### CDN uploaded! :rocket:" >> $GITHUB_STEP_SUMMARY
      - run: echo "${{ steps.upload.outputs.uploaded }}" >> $GITHUB_STEP_SUMMARY
