Copy to clipboard
@startuml
actor       "Student team"  as team
queue       "quiz-rapid"    as rapid
participant "Quizmaster"    as QM
participant "Quizboard"     as QB

group QM oppstart
    QM <- rapid: Leser inn meldinger for\nå oppdatere intern state
end

group question loop
    QM -> rapid: publish(question 1)
    rapid -> team: poll(question 1)
    team -> rapid: publish(answer 1)
    QM <- rapid: poll(answer 1)
    QM -> rapid: publish(assessment 1)

    group Quizboard only cares about assessments
    QB <- rapid: poll((assessment 1)
    QB -> QB: update leaderboard
    end
end

@enduml